version: "2"

linters:
  default: all
  disable:
    - wsl
    - wrapcheck
    - varnamelen
    - wastedassign
    - thelper
    - testpackage
    - testifylint
    - tagliatelle
    - perfsprint
    - paralleltest
    - nonamedreturns
    - recvcheck
    - mnd
    - ireturn
    - intrange
    - gochecknoglobals
    - inamedparam
    - forcetypeassert
    - fatcontext
    - exhaustruct
    - exhaustive
    - err113
    - errorlint
    - errchkjson
    - depguard
    - dupword
    - cyclop
    - gocyclo
    - copyloopvar
    - contextcheck
    - gomoddirectives
    - unparam
    - funlen
    - godox
    - gosec
    - containedctx
    - lll
    - nestif
    - maintidx
    - gocognit
    - dupl
    - errcheck
    - forbidigo
    - gochecknoinits
    - revive

  settings:
    nolintlint:
      allow-unused: false # report any unused nolint directives
      require-explanation: true # require an explanation for nolint directives
      require-specific: true # require nolint directives to mention the specific linter being suppressed
    goheader:
      template-path: ".github/.golangci.goheader.template"
      values:
        regexp:
          copyright-year: 20[2-9]\d

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
