project_name: lstn

release:
  prerelease: auto
  draft: false
  name_template: "listen.dev CLI v{{.Version}}"

before:
  hooks:
    - go mod tidy
    - go build -o make/make make/main.go
    - make/make man

# FIXME: use make/make lstn
builds:
  - <<: &build_defaults
      binary: lstn
      main: ./cmd/lstn
      env:
        - CGO_ENABLED=0
      flags:
        - -trimpath
      ldflags:
        - -w -s -X github.com/listendev/lstn/pkg/version.VersionPrefix=v{{.Version}}
    id: macos
    goos: [darwin]
    goarch: [arm64, amd64]

  - <<: *build_defaults
    id: linux
    goos: [linux]
    goarch: ["386", arm, amd64, arm64]

# Docs at https://goreleaser.com/customization/changelog
changelog:
  use: github-native
  sort: asc

# Docs at https://goreleaser.com/customization/sign
signs:
  - cmd: cosign
    signature: "${artifact}.sig"
    certificate: '{{ trimsuffix (trimsuffix .Env.artifact ".zip") ".tar.gz" }}.pem'
    args: ["sign-blob", "--yes", "--output-signature=${signature}", "--output-certificate=${certificate}", "${artifact}"]
    artifacts: all
    output: true
    env:
      - COSIGN_EXPERIMENTAL=1

# Docs at https://goreleaser.com/customization/sbom
sboms:
  - artifacts: binary
    documents:
      - >-
        {{ .ProjectName }}_
        {{- .Version }}_
        {{- if eq .Os "darwin" }}macos{{ else }}{{ .Os }}{{ end }}_
        {{- .Arch }}
        {{- with .Arm }}v{{ . }}{{ end }}
        {{- with .Mips }}_{{ . }}{{ end }}
        {{- if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}.sbom
    cmd: syft
    args: ["$artifact", "--file", "${document}", "--output", "cyclonedx-json"]

# Docs at https://goreleaser.com/customization/archive
archives:
  - id: nix
    builds: [macos, linux]
    <<: &archive_defaults
      name_template: >-
        {{ .ProjectName }}_
        {{- .Version }}_
        {{- if eq .Os "darwin" }}macos{{ else }}{{ .Os }}{{ end }}_
        {{- .Arch }}
        {{- with .Arm }}v{{ . }}{{ end }}
        {{- with .Mips }}_{{ . }}{{ end }}
        {{- if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}
    wrap_in_directory: true
    format: tar.gz
    files:
      - LICENSE
      - ./share/man/man1/lstn*
  # - id: win
  #   builds: [windows]
  #   <<: *archive_defaults
  #   wrap_in_directory: false
  #   format: zip
  #   files:
  #     - LICENSE

# # Docs at https://goreleaser.com/customization/nfpm
# nfpms:
#   - license: Apache 2.0
#     maintainer: Garnet Labs Inc.
#     homepage: https://github.com/listendev/lstn
#     description: |-
#       Analyze the behavior of your dependencies using listen.dev.
#     formats:
#       - apk
#       - deb
#       - rpm
#       - archlinux # Since GoReleaser v1.13
#    # TODO > add the manpages to the packages with the "contents" property