name: issues automation

on:
  issues:
    types: [opened]

permissions:
  contents: none
  issues: write

jobs:
  issue-auto:
    name: label issues
    runs-on: ubuntu-latest
    steps:
      - name: Label the new issue
        env:
          GH_REPO: ${{ github.repository }}
          GH_TOKEN: ${{ github.token }}
          ISSUENUM: ${{ github.event.issue.number }}
          ISSUEAUTHOR: ${{ github.event.issue.user.login }}
        run: |
          if ! gh api orgs/listendev/public_members/$ISSUEAUTHOR --silent 2>/dev/null
          then
            gh issue edit $ISSUENUM --add-label "needs-triage"
          fi