name: linting

on:
  push:
    paths:
      - "**.go"
      - go.mod
      - go.sum
    branches: ['main']
  pull_request:
    paths:
      - "**.go"
      - go.mod
      - go.sum
    branches: ['main']

permissions:
  contents: read

jobs:
  lint:
    name: "go"
    runs-on: ubuntu-latest

    steps:

      - name: Check out the source code
        uses: actions/checkout@v3

      - name: Set up Go 1.19
        uses: actions/setup-go@v4
        with:
          go-version: 1.19

      - name: Verify the dependencies
        run: |
          go mod verify
          go mod download

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.0