name: linting

on:
  push:
    paths:
      - "**.go"
      - go.mod
      - go.sum
    branches: ["main"]
  pull_request:
    paths:
      - "**.go"
      - go.mod
      - go.sum
    branches: ["main"]

permissions:
  contents: read

jobs:
  lint:
    name: "go"
    runs-on: ubuntu-latest

    steps:
      - name: Check out the source code
        uses: actions/checkout@v3

      - name: Lint
        uses: reviewdog/action-golangci-lint@v2
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          fail_on_error: true
          reporter: "github-check"