name: linting

on:
  push:
    paths:
      - "**.go"
      - go.mod
      - go.sum
    branches: ["main"]
  pull_request:
    paths:
      - "**.go"
      - go.mod
      - go.sum
    branches: ["main"]

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  lint:
    name: "go"
    runs-on: ubuntu-latest

    steps:
      - name: Check out the source code
        uses: actions/checkout@v4

      - name: Set up Go 1.21
        uses: actions/setup-go@v5
        with:
          go-version: "1.21"
          cache: false

      - name: Verify the dependencies
        run: |
          go mod verify
          go mod download

      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: v1.54
          args: --timeout 20m0s --verbose --out-${IGNORE_FUTURE_WARNINGS}format tab
          only-new-issues: true # Show only new issues on pull requests
